services:
  assessment-service:
    build: .
    container_name: assessment-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8003:8003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
